create database sample;
use sample;
CREATE TABLE Customer (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
EMAIL VARCHAR(100),
ADDRESS VARCHAR(150),
PRIMARY KEY (ID)
);
INSERT INTO Customer VALUES (1, "John Doe", "john@example.com", "123 Main St, Anytown");

CREATE TABLE Orders (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) UNIQUE,
PRIMARY KEY (ID)
);
INSERT INTO Orders VALUES (1, "ORDER-001");

CREATE TABLE Product (
ID INT NOT NULL AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(100),
UNIT_PRICE DOUBLE,
DISCOUNT DOUBLE,
TAX DOUBLE,
PRIMARY KEY(ID) 
);
INSERT INTO Product VALUES (1, "Product 1", 5, 1, 0.5), (2, "Product 2", 5, 1, 0.5);

CREATE TABLE Order_Details (
ID INT NOT NULL AUTO_INCREMENT,
PRODUCT_ID VARCHAR(100),
QUANTITY INT,
ORDER_ID INT,
PRIMARY KEY (ID),
CONSTRAINT `Order_Details_FK_ORDER_ID` FOREIGN KEY (ORDER_ID) REFERENCES Orders (ID) ON DELETE CASCADE 
);
INSERT INTO Order_Details VALUES (1, 1, 2, 1), (2, 2, 3, 1);


CREATE TABLE Invoice (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) UNIQUE,
ORDER_ID INT,
CUSTOMER_ID INT,
INVOICE_TOTAL DOUBLE,
PRIMARY KEY (ID)
);
INSERT INTO Invoice VALUES (1, "INV-001", 1, 1, 1);